<?php
/**
 * Created by PhpStorm.
 * User: lipenghui
 * Date: 2019-04-25
 * Time: 10:56
 */

namespace backend\models\command;


class CmdKick extends BaseCmd
{
    public $name="kick";
    public $playerName="wht";
    public $secretKey="longcitywebonline12345678901234567890";
    public $ip="111.231.60.73";
    public $port="8310";
    public function rules()
    {
        $parentRules=parent::rules(); // TODO: Change the autogenerated stub
        $myRules=[
            [['playerName'],'required'],
        ];
        return array_merge($parentRules,$myRules);
    }
    public function attributeLabels()
    {
        $parentLabels=parent::attributeLabels(); // TODO: Change the autogenerated stub
        $myLabels=[
            'playerName'=>'玩家名称'
        ];
        return array_merge($parentLabels,$myLabels);
    }

    /**
     * 构建命令
     */
    public function buildCommand()
    {
        $cmd=array_merge([$this->name],[$this->playerName]);
        $this->command=join(" ",$cmd);
    }
}