<?php
/**
 * Created by PhpStorm.
 * User: lipenghui
 * Date: 2019-04-26
 * Time: 10:02
 */

namespace backend\models\command;


use backend\models\TabAreas;
use backend\models\TabServers;
use yii\helpers\ArrayHelper;

class CmdMail extends BaseCmd
{
    public $gameid;
    public $pid;
    public $sid; //当是全区或单人的时候
    public $type;//单平台,全区,单人
    public $name="postmail";
    public $playerName;//玩家名称[名称前面需要加user:]或seedId，如果是全服邮件 则用"all"
    public $title;    //邮件标题
    public $content;  //邮件内容
    public $items;    //邮件附件：itemid,num,itemid,num格式

    public $secretKey="longcitywebonline12345678901234567890";
    public $ip="111.231.60.73";
    public $port=8310;
    public function rules()
    {
        $parentRules= parent::rules(); // TODO: Change the autogenerated stub
        $myRules=[
            [['playerName','title','content','gameid','pid'],'required'],
            [['sid'],'required','when'=>function($model){return $model->type>1;}],
            [['playerName','title','content','items','pid'],'string'],
            [['gameid'],'integer']
        ];
        return array_merge($parentRules,$myRules);
    }
    public function attributeLabels()
    {
        $parentLabels= parent::attributeLabels(); // TODO: Change the autogenerated stub
        $myLabels=[
            'playerName'=>\Yii::t('app','玩家名称'),
            'title'=>\Yii::t('app','邮件标题'),
            'content'=>\Yii::t('app','邮件正文'),
            'items'=>\Yii::t('app','附件'),
        ];
        return array_merge($parentLabels,$myLabels);
    }

    public function buildCommand()
    {
        $this->command=join(' ',[$this->name,"user:".$this->playerName,$this->title,$this->content,$this->items]);
    }
    public function buildServers()
    {
        $areaQuery=TabAreas::find()
            ->select(['id','port'=>'masterport','ip'=>'area_url'])
            ->where(['gameid'=>$this->gameid,'pt_flag'=>$this->pid,'is_hq'=>'0']);
        $serverQuery=TabServers::find()
            ->select(['areaid','name'])
            ->where(['gameid'=>$this->gameid,'pt_flag'=>$this->pid]);
        if ($this->type>1)
        {
           $areaQuery->where('0=1');
        }
        $this->serverList=$areaQuery->asArray()->all();
        $serverData=ArrayHelper::map($serverQuery->all(),'areaid','name');
        for ($i=0;$i<count($this->serverList);$i++)
        {
            $this->serverList[$i]['name']=$serverData[$this->serverList[$i]['id']];
        }

    }
}