<?php


namespace backend\models;


use Yii;
use yii\web\UploadedFile;

class MyTabGameItemdef extends TabGameItemdefLog
{
    public $file;
    private $fileName;
    private $fileSize;
    public function rules()
    {

        $myRules= [
            [['file'],'file','skipOnError'=>false,'extensions'=>'csv','maxSize'=>5242880],
        ];
        return array_merge(parent::rules(),$myRules); // TODO: Change the autogenerated stub
    }
    public function uploadItemdef()
    {
        $request=\Yii::$app->request;
        if ($this->load($request->bodyParams))
        {
            $fileInfo=UploadedFile::getInstance($this,'file');
            if ($fileInfo)
            {
                $this->fileName=$fileInfo->name;
                $this->fileSize=$fileInfo->size/1024;
            }else{
                echo("文件不存在");
                return false;
            }
            $dir="../web/uploads";
            if (!is_dir($dir))
            {
                mkdir($dir);
            }
            $dir="../web/uploads/data";
            if (!is_dir($dir))
            {
                mkdir($dir);
            }
            $dir=$dir."/".$this->fileName.".".$fileInfo->extension;
            if($fileInfo->saveAs($dir))
            {
                $file = fopen($dir,'r');
                $i=0;
//                头4行为描述信息，第一行为版本号；第二行为字段名称；第三行为数据类型；第四行为备注
//                TODO 生成表
                $fields=[];
                $types=[];
                $comments=[];

                $values=[];
                while (!feof($file))
                {
                    $list= explode("\t", @iconv('gb2312','utf-8',fgets($file)));//fgets()函数从文件指针中读取一行
                    $info=mb_split(",",trim($list[0]));

                    if ($i<4)
                    {
                        $info=mb_split(",",str_replace("#","",$list[0]));
                        switch ($i)
                        {
                            case 0:
//                                echo("版本:".$info[0]."<br>");
                                break;
                            case 1: //表字段
                                $temp=[];
                                for ($k=0;$k<count($info);$k++)
                                {
                                    $temp[]=trim($info[$k]);
                                }
                                $fields=$temp;
                                break;
                            case 2: //字段类型
                                $types=$info;
                                break;
                            case 3: //字段描述
                                $comments=$info;
                                break;
                        }
                    }
                    else if($i==4)
                    {
                        //创建表
                        $sql="DROP TABLE IF EXISTS `tab_itemdef_".$this->gameId."`; CREATE TABLE `tab_itemdef_".$this->gameId."` (";
                        $sqlFields=[];
                        for ($j=0;$j<count($fields);$j++)
                        {
                            $field=$fields[$j];
                            $type=$types[$j];
                            $sqlType='int(11)';
                            $comment=$comments[$j];
                            switch (trim($type))
                            {
                                case 'int':
                                    $sqlType='int(11)';
                                    break;
                                case 'string':
                                    $sqlType='varchar(255)';
                                    break;
                            }
                            $sqlFields[]="`".trim($field)."` ".$sqlType." COMMENT '$comment'";
                        }
                        if (count($sqlFields)>0)
                        {
                            $sql=$sql.join(",",$sqlFields).") ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;";
                            $query=Yii::$app->get('db_log')->createCommand($sql);
                            $query->execute();
                            $query->pdoStatement->closeCursor();
                        }else{
                            return false;
                        }
                        $sqlFields=null;
                    }
                    else{
                        $id=$info[0];
                        if(substr($id,0,1)!="#" && trim($id)!="")
                        {
                            //构建需要插入的数据
                            array_push($values,$info);
                        }
                    }
                    $i++;
                }
                fclose($file);
                //批量插入数据
                if (count($values)>0){
                    $db=Yii::$app->get('db_log');
                    $cmd=$db->createCommand();
                    $cmd->batchInsert("tab_itemdef_".$this->gameId,$fields,$values);
                    $cmd->query();
                }
            }else{
                echo(json_encode($this->getErrors()));
                return false;
            }
        }
        return true;
    }
}