<?php
/**
 * Created by PhpStorm.
 * User: lipenghui
 * Date: 2019-05-08
 * Time: 09:53
 */

namespace backend\controllers\center;

/**
 * Class YijieController 易接接口
 * @package backend\controllers\center
 */
class YijieController extends CenterController
{
    public function loginValidate($request,$distributor)
    {
        //正式地址
        $login_url='http://sync.1sdk.cn/login/check.html?';
        //TODO 需要确认一下 sdk 跟 app 两个参数对应的值
        $body = array(
            'sdk'=>$request['sdk'],
            'app'=>$request['app'],
            'uin'=>$request['accountId'],
            'sess'=>$request['token']
        );

        $param=http_build_query($body);
        $response = execRequest($login_url.$param);
        if ($response==0) {
            $player = array(
                'distributorPlayerId' => $request['accountId'],
                'nickname'            => $request['accountId'],
                'distributor'         => $distributor->distributor,
            );
            return $player;
        }
        return null;
    }
    public function orderValidate($request,$distributor)
    {
//        return parent::orderValidate(); // TODO: Change the autogenerated stub
//        $param = array(
//            'app' => $request['app'],
//            'cbi'=>$request['cbi'],
//            'ct'=>$request['ct'],
//            'fee'=>$request['fee'],
//            'pt'=>$request['pt'],
//            'sdk'=>$request['sdk'],
//            'ssid'=>$request['ssid'],
//            'st'=>$request['st'],
//            'tcd'=>$request['tcd'],
//            'uid'=>$request['uid'],
//            'ver'=>$request['ver']
//        );
//        $sign=$request['sign'];
//
//        ksort($param);
//        $temp=array();
//        foreach($param as $k=>$v)
//        {
//            $str=$k.'='.$v;
//            array_push($temp,$str);
//        }
//        $signStr=join("&",$temp);
//        $mySign=md5($signStr.$secretKey);
//        if ($mySign==$sign && $request['st']==1) {
//            return true;
//        }else
//        {
//            return false;
//        }
    }
}